version: '3.8'

services:
  app:
    build:
      context: .  # Current directory (root directory where Dockerfile and package.json are located)
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DB_HOST: db
      REDIS_HOST: redis
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: kam_user
      POSTGRES_PASSWORD: secure_password
      POSTGRES_DB: kam_management
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
